//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class Item : EntityBase
    {
        public Item()
        {
            this.ItemDosages = new ObservableCollection<ItemDosage>();
            this.TransactionEntryItems = new ObservableCollection<TransactionEntryItem>();
            CustomStartup();
            this.PropertyChanged += UpdatePropertyChanged;
            
        }
        partial void CustomStartup();
    
            private void UpdatePropertyChanged(object sender, PropertyChangedEventArgs e)
            {
                if (!string.IsNullOrEmpty(e.PropertyName) && (!Environment.StackTrace.Contains("Internal.Materialization")) && TrackingState == TrackingState.Unchanged)
                {
                    TrackingState = TrackingState.Modified;
                }
            }
    
            ChangeTrackingCollection<Item> _changeTracker;
    
            [NotMapped]
            [IgnoreDataMember]
            public ChangeTrackingCollection<Item> ChangeTracker
            {
                get
                {
                    return _changeTracker;
                }
            }
            
            public new void StartTracking()
            {
                _changeTracker = new ChangeTrackingCollection<Item>(this);
            }
        [DataMember]
    	public string Description
    	{ 
    		get { return _Description; }
    		set
    		{
    			if (Equals(value, _Description)) return;
    			_Description = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Description;
        [DataMember]
    	public Nullable<bool> ItemNotDiscountable
    	{ 
    		get { return _ItemNotDiscountable; }
    		set
    		{
    			if (Equals(value, _ItemNotDiscountable)) return;
    			_ItemNotDiscountable = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<bool> _ItemNotDiscountable;
        [DataMember]
    	public int ItemId
    	{ 
    		get { return _ItemId; }
    		set
    		{
    			if (Equals(value, _ItemId)) return;
    			_ItemId = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private int _ItemId;
        [DataMember]
    	public string ItemLookupCode
    	{ 
    		get { return _ItemLookupCode; }
    		set
    		{
    			if (Equals(value, _ItemLookupCode)) return;
    			_ItemLookupCode = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _ItemLookupCode;
        [DataMember]
    	public string Department
    	{ 
    		get { return _Department; }
    		set
    		{
    			if (Equals(value, _Department)) return;
    			_Department = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Department;
        [DataMember]
    	public string Category
    	{ 
    		get { return _Category; }
    		set
    		{
    			if (Equals(value, _Category)) return;
    			_Category = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Category;
        [DataMember]
    	public double Price
    	{ 
    		get { return _Price; }
    		set
    		{
    			if (Equals(value, _Price)) return;
    			_Price = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private double _Price;
        [DataMember]
    	public Nullable<double> Cost
    	{ 
    		get { return _Cost; }
    		set
    		{
    			if (Equals(value, _Cost)) return;
    			_Cost = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<double> _Cost;
        [DataMember]
    	public double Quantity
    	{ 
    		get { return _Quantity; }
    		set
    		{
    			if (Equals(value, _Quantity)) return;
    			_Quantity = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private double _Quantity;
        [DataMember]
    	public string ExtendedDescription
    	{ 
    		get { return _ExtendedDescription; }
    		set
    		{
    			if (Equals(value, _ExtendedDescription)) return;
    			_ExtendedDescription = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _ExtendedDescription;
        [DataMember]
    	public Nullable<bool> Inactive
    	{ 
    		get { return _Inactive; }
    		set
    		{
    			if (Equals(value, _Inactive)) return;
    			_Inactive = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<bool> _Inactive;
        [DataMember]
    	public Nullable<System.DateTime> DateCreated
    	{ 
    		get { return _DateCreated; }
    		set
    		{
    			if (Equals(value, _DateCreated)) return;
    			_DateCreated = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<System.DateTime> _DateCreated;
        [DataMember]
    	public Nullable<double> SalesTax
    	{ 
    		get { return _SalesTax; }
    		set
    		{
    			if (Equals(value, _SalesTax)) return;
    			_SalesTax = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private Nullable<double> _SalesTax;
        [DataMember]
    	public string QBItemListID
    	{ 
    		get { return _QBItemListID; }
    		set
    		{
    			if (Equals(value, _QBItemListID)) return;
    			_QBItemListID = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _QBItemListID;
        [DataMember]
    	public string UnitOfMeasure
    	{ 
    		get { return _UnitOfMeasure; }
    		set
    		{
    			if (Equals(value, _UnitOfMeasure)) return;
    			_UnitOfMeasure = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _UnitOfMeasure;
        [DataMember]
    	public string ItemName
    	{ 
    		get { return _ItemName; }
    		set
    		{
    			if (Equals(value, _ItemName)) return;
    			_ItemName = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _ItemName;
        [DataMember]
    	public string ItemNumber
    	{ 
    		get { return _ItemNumber; }
    		set
    		{
    			if (Equals(value, _ItemNumber)) return;
    			_ItemNumber = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _ItemNumber;
        [DataMember]
    	public string Size
    	{ 
    		get { return _Size; }
    		set
    		{
    			if (Equals(value, _Size)) return;
    			_Size = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Size;
        [DataMember]
    	public byte[] EntryTimeStamp
    	{ 
    		get { return _EntryTimeStamp; }
    		set
    		{
    			if (Equals(value, _EntryTimeStamp)) return;
    			_EntryTimeStamp = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private byte[] _EntryTimeStamp;
        [DataMember]
    	public QBInventoryItem QBInventoryItem
    	{
    		get { return _QBInventoryItem; }
    		set
    		{
    			if (Equals(value, _QBInventoryItem)) return;
    			_QBInventoryItem = value;
    			QBInventoryItemChangeTracker = _QBInventoryItem == null ? null
    				: new ChangeTrackingCollection<QBInventoryItem> { _QBInventoryItem };
    			NotifyPropertyChanged();
    		}
    	}
    	private QBInventoryItem _QBInventoryItem;
    	private ChangeTrackingCollection<QBInventoryItem> QBInventoryItemChangeTracker { get; set; }
        [DataMember]
    	public ObservableCollection<ItemDosage> ItemDosages
    	{
    		get { return _ItemDosages; }
    		set
    		{
    			if (Equals(value, _ItemDosages)) return;
    			_ItemDosages = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private ObservableCollection<ItemDosage> _ItemDosages;
        [DataMember]
    	public ObservableCollection<TransactionEntryItem> TransactionEntryItems
    	{
    		get { return _TransactionEntryItems; }
    		set
    		{
    			if (Equals(value, _TransactionEntryItems)) return;
    			_TransactionEntryItems = value;
    			NotifyPropertyChanged();
    		}
    	}
    	private ObservableCollection<TransactionEntryItem> _TransactionEntryItems;
    }
}
